/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface BrokerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FEE_TYPEHASH"
      | "UPGRADE_INTERFACE_VERSION"
      | "acceptOwnership"
      | "activeFeeTiers"
      | "adjustCollateral"
      | "cancelOrder"
      | "cancelOrders"
      | "claimRebate"
      | "claimRebates"
      | "eip712Domain"
      | "getAddOnFeeTier"
      | "getAddressManager"
      | "getDependencyAddress"
      | "getDependencyIdentifier"
      | "getImplementation"
      | "getUserFeeRate"
      | "initialize"
      | "isActive"
      | "name"
      | "onBrokerFee"
      | "owner"
      | "pendingOwner"
      | "placeOrder"
      | "proxiableUUID"
      | "registerDependencies"
      | "renounceOwnership"
      | "setSigner"
      | "setUserFeeData"
      | "transferOwnership"
      | "unregisterDependencies"
      | "updateBrokerStatus"
      | "updateFeeTier"
      | "updateFeeTiers"
      | "updateOrder"
      | "upgradeTo"
      | "upgradeToAndCall"
      | "userFeeData"
      | "userRebates"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddOnFeeTierUpdated"
      | "BrokerStatusUpdated"
      | "EIP712DomainChanged"
      | "Initialized"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "RebateClaimed"
      | "SignerUpdated"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "FEE_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeFeeTiers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "adjustCollateral",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOrders",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRebate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRebates",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAddOnFeeTier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddressManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDependencyAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDependencyIdentifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserFeeRate",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      AddressLike,
      AddressLike,
      string,
      AddressLike[],
      BigNumberish[],
      { takerFeeRate: BigNumberish; makerFeeRate: BigNumberish }[]
    ]
  ): string;
  encodeFunctionData(functionFragment: "isActive", values?: undefined): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "onBrokerFee",
    values: [BytesLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "placeOrder",
    values: [
      {
        user: AddressLike;
        poolId: BytesLike;
        positionId: BigNumberish;
        orderType: BigNumberish;
        triggerType: BigNumberish;
        operation: BigNumberish;
        direction: BigNumberish;
        collateralAmount: BigNumberish;
        size: BigNumberish;
        orderPrice: BigNumberish;
        triggerPrice: BigNumberish;
        timeInForce: BigNumberish;
        postOnly: boolean;
        slippagePct: BigNumberish;
        executionFeeToken: AddressLike;
        leverage: BigNumberish;
        tpSize: BigNumberish;
        tpPrice: BigNumberish;
        slSize: BigNumberish;
        slPrice: BigNumberish;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerDependencies",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setSigner",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setUserFeeData",
    values: [
      AddressLike,
      BigNumberish,
      {
        tier: BigNumberish;
        referrer: AddressLike;
        totalReferralRebatePct: BigNumberish;
        referrerRebatePct: BigNumberish;
      },
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unregisterDependencies",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBrokerStatus",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFeeTier",
    values: [
      BigNumberish,
      { takerFeeRate: BigNumberish; makerFeeRate: BigNumberish }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFeeTiers",
    values: [
      BigNumberish[],
      { takerFeeRate: BigNumberish; makerFeeRate: BigNumberish }[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateOrder",
    values: [
      {
        orderId: BigNumberish;
        tpSize: BigNumberish;
        tpPrice: BigNumberish;
        slSize: BigNumberish;
        slPrice: BigNumberish;
        executionFeeToken: AddressLike;
        useOrderCollateral: boolean;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userFeeData",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userRebates",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "FEE_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeFeeTiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adjustCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRebate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRebates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAddOnFeeTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAddressManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDependencyAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDependencyIdentifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isActive", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onBrokerFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "placeOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerDependencies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setSigner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setUserFeeData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unregisterDependencies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBrokerStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFeeTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFeeTiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userFeeData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userRebates",
    data: BytesLike
  ): Result;
}

export namespace AddOnFeeTierUpdatedEvent {
  export type InputTuple = [
    broker: AddressLike,
    tier: BigNumberish,
    takerFeeRate: BigNumberish,
    makerFeeRate: BigNumberish
  ];
  export type OutputTuple = [
    broker: string,
    tier: bigint,
    takerFeeRate: bigint,
    makerFeeRate: bigint
  ];
  export interface OutputObject {
    broker: string;
    tier: bigint;
    takerFeeRate: bigint;
    makerFeeRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BrokerStatusUpdatedEvent {
  export type InputTuple = [broker: AddressLike, isActive: boolean];
  export type OutputTuple = [broker: string, isActive: boolean];
  export interface OutputObject {
    broker: string;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RebateClaimedEvent {
  export type InputTuple = [
    user: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [user: string, token: string, amount: bigint];
  export interface OutputObject {
    user: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignerUpdatedEvent {
  export type InputTuple = [signer: AddressLike, isSigner: boolean];
  export type OutputTuple = [signer: string, isSigner: boolean];
  export interface OutputObject {
    signer: string;
    isSigner: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Broker extends BaseContract {
  connect(runner?: ContractRunner | null): Broker;
  waitForDeployment(): Promise<this>;

  interface: BrokerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FEE_TYPEHASH: TypedContractMethod<[], [string], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  activeFeeTiers: TypedContractMethod<[], [bigint[]], "view">;

  adjustCollateral: TypedContractMethod<
    [positionId: BigNumberish, adjustAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelOrders: TypedContractMethod<
    [orderIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  claimRebate: TypedContractMethod<[token: AddressLike], [void], "nonpayable">;

  claimRebates: TypedContractMethod<
    [tokens: AddressLike[]],
    [void],
    "nonpayable"
  >;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  getAddOnFeeTier: TypedContractMethod<
    [tier: BigNumberish],
    [[bigint, bigint] & { takerFeeRate: bigint; makerFeeRate: bigint }],
    "view"
  >;

  getAddressManager: TypedContractMethod<[], [string], "view">;

  getDependencyAddress: TypedContractMethod<
    [identifier: BytesLike],
    [string],
    "view"
  >;

  getDependencyIdentifier: TypedContractMethod<
    [contractAddress: AddressLike],
    [string],
    "view"
  >;

  getImplementation: TypedContractMethod<[], [string], "view">;

  getUserFeeRate: TypedContractMethod<
    [user: AddressLike, assetClass: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        takerFeeRate: bigint;
        makerFeeRate: bigint;
        baseTakerFeeRate: bigint;
        baseMakerFeeRate: bigint;
      }
    ],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      addressManager: AddressLike,
      owner: AddressLike,
      _brokerName: string,
      brokerSigners: AddressLike[],
      assetClasses: BigNumberish[],
      baseFeeRates: { takerFeeRate: BigNumberish; makerFeeRate: BigNumberish }[]
    ],
    [void],
    "nonpayable"
  >;

  isActive: TypedContractMethod<[], [boolean], "view">;

  name: TypedContractMethod<[], [string], "view">;

  onBrokerFee: TypedContractMethod<
    [
      poolId: BytesLike,
      user: AddressLike,
      token: AddressLike,
      feeAmount: BigNumberish
    ],
    [
      [bigint, bigint, string] & {
        totalReferralRebate: bigint;
        referrerRebate: bigint;
        referrer: string;
      }
    ],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  placeOrder: TypedContractMethod<
    [
      orderParams: {
        user: AddressLike;
        poolId: BytesLike;
        positionId: BigNumberish;
        orderType: BigNumberish;
        triggerType: BigNumberish;
        operation: BigNumberish;
        direction: BigNumberish;
        collateralAmount: BigNumberish;
        size: BigNumberish;
        orderPrice: BigNumberish;
        triggerPrice: BigNumberish;
        timeInForce: BigNumberish;
        postOnly: boolean;
        slippagePct: BigNumberish;
        executionFeeToken: AddressLike;
        leverage: BigNumberish;
        tpSize: BigNumberish;
        tpPrice: BigNumberish;
        slSize: BigNumberish;
        slPrice: BigNumberish;
      }
    ],
    [void],
    "payable"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  registerDependencies: TypedContractMethod<
    [identifiers: BytesLike[]],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setSigner: TypedContractMethod<
    [signer: AddressLike, isSigner: boolean],
    [void],
    "nonpayable"
  >;

  setUserFeeData: TypedContractMethod<
    [
      user: AddressLike,
      deadline: BigNumberish,
      feeData: {
        tier: BigNumberish;
        referrer: AddressLike;
        totalReferralRebatePct: BigNumberish;
        referrerRebatePct: BigNumberish;
      },
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unregisterDependencies: TypedContractMethod<
    [identifiers: BytesLike[]],
    [void],
    "nonpayable"
  >;

  updateBrokerStatus: TypedContractMethod<
    [active: boolean],
    [void],
    "nonpayable"
  >;

  updateFeeTier: TypedContractMethod<
    [
      tier: BigNumberish,
      feeRate: { takerFeeRate: BigNumberish; makerFeeRate: BigNumberish }
    ],
    [void],
    "nonpayable"
  >;

  updateFeeTiers: TypedContractMethod<
    [
      tiers: BigNumberish[],
      feeRates: { takerFeeRate: BigNumberish; makerFeeRate: BigNumberish }[]
    ],
    [void],
    "nonpayable"
  >;

  updateOrder: TypedContractMethod<
    [
      params: {
        orderId: BigNumberish;
        tpSize: BigNumberish;
        tpPrice: BigNumberish;
        slSize: BigNumberish;
        slPrice: BigNumberish;
        executionFeeToken: AddressLike;
        useOrderCollateral: boolean;
      }
    ],
    [void],
    "nonpayable"
  >;

  upgradeTo: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  userFeeData: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, string, bigint, bigint] & {
        tier: bigint;
        referrer: string;
        totalReferralRebatePct: bigint;
        referrerRebatePct: bigint;
      }
    ],
    "view"
  >;

  userRebates: TypedContractMethod<
    [user: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FEE_TYPEHASH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "activeFeeTiers"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "adjustCollateral"
  ): TypedContractMethod<
    [positionId: BigNumberish, adjustAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelOrder"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelOrders"
  ): TypedContractMethod<[orderIds: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRebate"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRebates"
  ): TypedContractMethod<[tokens: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAddOnFeeTier"
  ): TypedContractMethod<
    [tier: BigNumberish],
    [[bigint, bigint] & { takerFeeRate: bigint; makerFeeRate: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAddressManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getDependencyAddress"
  ): TypedContractMethod<[identifier: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getDependencyIdentifier"
  ): TypedContractMethod<[contractAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getImplementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getUserFeeRate"
  ): TypedContractMethod<
    [user: AddressLike, assetClass: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        takerFeeRate: bigint;
        makerFeeRate: bigint;
        baseTakerFeeRate: bigint;
        baseMakerFeeRate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      addressManager: AddressLike,
      owner: AddressLike,
      _brokerName: string,
      brokerSigners: AddressLike[],
      assetClasses: BigNumberish[],
      baseFeeRates: { takerFeeRate: BigNumberish; makerFeeRate: BigNumberish }[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isActive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "onBrokerFee"
  ): TypedContractMethod<
    [
      poolId: BytesLike,
      user: AddressLike,
      token: AddressLike,
      feeAmount: BigNumberish
    ],
    [
      [bigint, bigint, string] & {
        totalReferralRebate: bigint;
        referrerRebate: bigint;
        referrer: string;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "placeOrder"
  ): TypedContractMethod<
    [
      orderParams: {
        user: AddressLike;
        poolId: BytesLike;
        positionId: BigNumberish;
        orderType: BigNumberish;
        triggerType: BigNumberish;
        operation: BigNumberish;
        direction: BigNumberish;
        collateralAmount: BigNumberish;
        size: BigNumberish;
        orderPrice: BigNumberish;
        triggerPrice: BigNumberish;
        timeInForce: BigNumberish;
        postOnly: boolean;
        slippagePct: BigNumberish;
        executionFeeToken: AddressLike;
        leverage: BigNumberish;
        tpSize: BigNumberish;
        tpPrice: BigNumberish;
        slSize: BigNumberish;
        slPrice: BigNumberish;
      }
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerDependencies"
  ): TypedContractMethod<[identifiers: BytesLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSigner"
  ): TypedContractMethod<
    [signer: AddressLike, isSigner: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setUserFeeData"
  ): TypedContractMethod<
    [
      user: AddressLike,
      deadline: BigNumberish,
      feeData: {
        tier: BigNumberish;
        referrer: AddressLike;
        totalReferralRebatePct: BigNumberish;
        referrerRebatePct: BigNumberish;
      },
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unregisterDependencies"
  ): TypedContractMethod<[identifiers: BytesLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateBrokerStatus"
  ): TypedContractMethod<[active: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateFeeTier"
  ): TypedContractMethod<
    [
      tier: BigNumberish,
      feeRate: { takerFeeRate: BigNumberish; makerFeeRate: BigNumberish }
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateFeeTiers"
  ): TypedContractMethod<
    [
      tiers: BigNumberish[],
      feeRates: { takerFeeRate: BigNumberish; makerFeeRate: BigNumberish }[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateOrder"
  ): TypedContractMethod<
    [
      params: {
        orderId: BigNumberish;
        tpSize: BigNumberish;
        tpPrice: BigNumberish;
        slSize: BigNumberish;
        slPrice: BigNumberish;
        executionFeeToken: AddressLike;
        useOrderCollateral: boolean;
      }
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeTo"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "userFeeData"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, string, bigint, bigint] & {
        tier: bigint;
        referrer: string;
        totalReferralRebatePct: bigint;
        referrerRebatePct: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "userRebates"
  ): TypedContractMethod<
    [user: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;

  getEvent(
    key: "AddOnFeeTierUpdated"
  ): TypedContractEvent<
    AddOnFeeTierUpdatedEvent.InputTuple,
    AddOnFeeTierUpdatedEvent.OutputTuple,
    AddOnFeeTierUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "BrokerStatusUpdated"
  ): TypedContractEvent<
    BrokerStatusUpdatedEvent.InputTuple,
    BrokerStatusUpdatedEvent.OutputTuple,
    BrokerStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RebateClaimed"
  ): TypedContractEvent<
    RebateClaimedEvent.InputTuple,
    RebateClaimedEvent.OutputTuple,
    RebateClaimedEvent.OutputObject
  >;
  getEvent(
    key: "SignerUpdated"
  ): TypedContractEvent<
    SignerUpdatedEvent.InputTuple,
    SignerUpdatedEvent.OutputTuple,
    SignerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "AddOnFeeTierUpdated(address,uint8,uint32,uint32)": TypedContractEvent<
      AddOnFeeTierUpdatedEvent.InputTuple,
      AddOnFeeTierUpdatedEvent.OutputTuple,
      AddOnFeeTierUpdatedEvent.OutputObject
    >;
    AddOnFeeTierUpdated: TypedContractEvent<
      AddOnFeeTierUpdatedEvent.InputTuple,
      AddOnFeeTierUpdatedEvent.OutputTuple,
      AddOnFeeTierUpdatedEvent.OutputObject
    >;

    "BrokerStatusUpdated(address,bool)": TypedContractEvent<
      BrokerStatusUpdatedEvent.InputTuple,
      BrokerStatusUpdatedEvent.OutputTuple,
      BrokerStatusUpdatedEvent.OutputObject
    >;
    BrokerStatusUpdated: TypedContractEvent<
      BrokerStatusUpdatedEvent.InputTuple,
      BrokerStatusUpdatedEvent.OutputTuple,
      BrokerStatusUpdatedEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RebateClaimed(address,address,uint256)": TypedContractEvent<
      RebateClaimedEvent.InputTuple,
      RebateClaimedEvent.OutputTuple,
      RebateClaimedEvent.OutputObject
    >;
    RebateClaimed: TypedContractEvent<
      RebateClaimedEvent.InputTuple,
      RebateClaimedEvent.OutputTuple,
      RebateClaimedEvent.OutputObject
    >;

    "SignerUpdated(address,bool)": TypedContractEvent<
      SignerUpdatedEvent.InputTuple,
      SignerUpdatedEvent.OutputTuple,
      SignerUpdatedEvent.OutputObject
    >;
    SignerUpdated: TypedContractEvent<
      SignerUpdatedEvent.InputTuple,
      SignerUpdatedEvent.OutputTuple,
      SignerUpdatedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
