/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface LiquidityRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "addTpsl"
      | "cancelTpsl"
      | "claimRebate"
      | "claimRebates"
      | "currentOrderId"
      | "depositBase"
      | "depositQuote"
      | "executeTpsl"
      | "getAddressManager"
      | "getDependencyAddress"
      | "getDependencyIdentifier"
      | "getImplementation"
      | "getTpslData"
      | "getUserTpslOrderIds"
      | "initialize"
      | "migrateLiquidity"
      | "proxiableUUID"
      | "registerDependencies"
      | "unregisterDependencies"
      | "upgradeTo"
      | "upgradeToAndCall"
      | "withdrawBase"
      | "withdrawQuote"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Initialized" | "Upgraded"): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addTpsl",
    values: [
      {
        poolId: BytesLike;
        poolType: BigNumberish;
        tpslParams: {
          amount: BigNumberish;
          triggerPrice: BigNumberish;
          triggerType: BigNumberish;
          minQuoteOut: BigNumberish;
        }[];
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTpsl",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRebate",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRebates",
    values: [BytesLike[], AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "currentOrderId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositBase",
    values: [
      {
        poolId: BytesLike;
        amountIn: BigNumberish;
        minAmountOut: BigNumberish;
        recipient: AddressLike;
        tpslParams: {
          amount: BigNumberish;
          triggerPrice: BigNumberish;
          triggerType: BigNumberish;
          minQuoteOut: BigNumberish;
        }[];
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositQuote",
    values: [
      {
        poolId: BytesLike;
        amountIn: BigNumberish;
        minAmountOut: BigNumberish;
        recipient: AddressLike;
        tpslParams: {
          amount: BigNumberish;
          triggerPrice: BigNumberish;
          triggerType: BigNumberish;
          minQuoteOut: BigNumberish;
        }[];
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeTpsl",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddressManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDependencyAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDependencyIdentifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTpslData",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTpslOrderIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "migrateLiquidity",
    values: [
      {
        fromPoolId: BytesLike;
        toPoolId: BytesLike;
        amount: BigNumberish;
        minLpOut: BigNumberish;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerDependencies",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "unregisterDependencies",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawBase",
    values: [
      {
        poolId: BytesLike;
        amountIn: BigNumberish;
        minAmountOut: BigNumberish;
        recipient: AddressLike;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawQuote",
    values: [
      {
        poolId: BytesLike;
        amountIn: BigNumberish;
        minAmountOut: BigNumberish;
        recipient: AddressLike;
      }
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addTpsl", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelTpsl", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimRebate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRebates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentOrderId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositBase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTpsl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAddressManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDependencyAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDependencyIdentifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTpslData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTpslOrderIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "migrateLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerDependencies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unregisterDependencies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawBase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawQuote",
    data: BytesLike
  ): Result;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LiquidityRouter extends BaseContract {
  connect(runner?: ContractRunner | null): LiquidityRouter;
  waitForDeployment(): Promise<this>;

  interface: LiquidityRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  addTpsl: TypedContractMethod<
    [
      params: {
        poolId: BytesLike;
        poolType: BigNumberish;
        tpslParams: {
          amount: BigNumberish;
          triggerPrice: BigNumberish;
          triggerType: BigNumberish;
          minQuoteOut: BigNumberish;
        }[];
      }
    ],
    [void],
    "nonpayable"
  >;

  cancelTpsl: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimRebate: TypedContractMethod<
    [poolId: BytesLike, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  claimRebates: TypedContractMethod<
    [poolIds: BytesLike[], recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  currentOrderId: TypedContractMethod<[], [bigint], "view">;

  depositBase: TypedContractMethod<
    [
      params: {
        poolId: BytesLike;
        amountIn: BigNumberish;
        minAmountOut: BigNumberish;
        recipient: AddressLike;
        tpslParams: {
          amount: BigNumberish;
          triggerPrice: BigNumberish;
          triggerType: BigNumberish;
          minQuoteOut: BigNumberish;
        }[];
      }
    ],
    [void],
    "nonpayable"
  >;

  depositQuote: TypedContractMethod<
    [
      params: {
        poolId: BytesLike;
        amountIn: BigNumberish;
        minAmountOut: BigNumberish;
        recipient: AddressLike;
        tpslParams: {
          amount: BigNumberish;
          triggerPrice: BigNumberish;
          triggerType: BigNumberish;
          minQuoteOut: BigNumberish;
        }[];
      }
    ],
    [void],
    "nonpayable"
  >;

  executeTpsl: TypedContractMethod<
    [orderId: BigNumberish, quoteIn: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAddressManager: TypedContractMethod<[], [string], "view">;

  getDependencyAddress: TypedContractMethod<
    [identifier: BytesLike],
    [string],
    "view"
  >;

  getDependencyIdentifier: TypedContractMethod<
    [contractAddress: AddressLike],
    [string],
    "view"
  >;

  getImplementation: TypedContractMethod<[], [string], "view">;

  getTpslData: TypedContractMethod<
    [orderId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint] & {
        user: string;
        poolId: string;
        poolType: bigint;
        amount: bigint;
        triggerPrice: bigint;
        triggerType: bigint;
        minQuoteOut: bigint;
      }
    ],
    "view"
  >;

  getUserTpslOrderIds: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  initialize: TypedContractMethod<
    [addressManager: AddressLike],
    [void],
    "nonpayable"
  >;

  migrateLiquidity: TypedContractMethod<
    [
      params: {
        fromPoolId: BytesLike;
        toPoolId: BytesLike;
        amount: BigNumberish;
        minLpOut: BigNumberish;
      }
    ],
    [void],
    "nonpayable"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  registerDependencies: TypedContractMethod<
    [identifiers: BytesLike[]],
    [void],
    "nonpayable"
  >;

  unregisterDependencies: TypedContractMethod<
    [identifiers: BytesLike[]],
    [void],
    "nonpayable"
  >;

  upgradeTo: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  withdrawBase: TypedContractMethod<
    [
      params: {
        poolId: BytesLike;
        amountIn: BigNumberish;
        minAmountOut: BigNumberish;
        recipient: AddressLike;
      }
    ],
    [void],
    "nonpayable"
  >;

  withdrawQuote: TypedContractMethod<
    [
      params: {
        poolId: BytesLike;
        amountIn: BigNumberish;
        minAmountOut: BigNumberish;
        recipient: AddressLike;
      }
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addTpsl"
  ): TypedContractMethod<
    [
      params: {
        poolId: BytesLike;
        poolType: BigNumberish;
        tpslParams: {
          amount: BigNumberish;
          triggerPrice: BigNumberish;
          triggerType: BigNumberish;
          minQuoteOut: BigNumberish;
        }[];
      }
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelTpsl"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRebate"
  ): TypedContractMethod<
    [poolId: BytesLike, recipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimRebates"
  ): TypedContractMethod<
    [poolIds: BytesLike[], recipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "currentOrderId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositBase"
  ): TypedContractMethod<
    [
      params: {
        poolId: BytesLike;
        amountIn: BigNumberish;
        minAmountOut: BigNumberish;
        recipient: AddressLike;
        tpslParams: {
          amount: BigNumberish;
          triggerPrice: BigNumberish;
          triggerType: BigNumberish;
          minQuoteOut: BigNumberish;
        }[];
      }
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositQuote"
  ): TypedContractMethod<
    [
      params: {
        poolId: BytesLike;
        amountIn: BigNumberish;
        minAmountOut: BigNumberish;
        recipient: AddressLike;
        tpslParams: {
          amount: BigNumberish;
          triggerPrice: BigNumberish;
          triggerType: BigNumberish;
          minQuoteOut: BigNumberish;
        }[];
      }
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeTpsl"
  ): TypedContractMethod<
    [orderId: BigNumberish, quoteIn: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAddressManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getDependencyAddress"
  ): TypedContractMethod<[identifier: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getDependencyIdentifier"
  ): TypedContractMethod<[contractAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getImplementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTpslData"
  ): TypedContractMethod<
    [orderId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint] & {
        user: string;
        poolId: string;
        poolType: bigint;
        amount: bigint;
        triggerPrice: bigint;
        triggerType: bigint;
        minQuoteOut: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserTpslOrderIds"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[addressManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "migrateLiquidity"
  ): TypedContractMethod<
    [
      params: {
        fromPoolId: BytesLike;
        toPoolId: BytesLike;
        amount: BigNumberish;
        minLpOut: BigNumberish;
      }
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerDependencies"
  ): TypedContractMethod<[identifiers: BytesLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unregisterDependencies"
  ): TypedContractMethod<[identifiers: BytesLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeTo"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "withdrawBase"
  ): TypedContractMethod<
    [
      params: {
        poolId: BytesLike;
        amountIn: BigNumberish;
        minAmountOut: BigNumberish;
        recipient: AddressLike;
      }
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawQuote"
  ): TypedContractMethod<
    [
      params: {
        poolId: BytesLike;
        amountIn: BigNumberish;
        minAmountOut: BigNumberish;
        recipient: AddressLike;
      }
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
