/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PoolConfiguratorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "benchPool"
      | "getAddressManager"
      | "getDependencyAddress"
      | "getDependencyIdentifier"
      | "getImplementation"
      | "initialize"
      | "perBenchPool"
      | "primePool"
      | "proxiableUUID"
      | "registerDependencies"
      | "trenchPool"
      | "unregisterDependencies"
      | "updatePoolCompoundEnabled"
      | "updatePoolPriceDeviations"
      | "updatePoolRiskTiers"
      | "updatePoolWindowCaps"
      | "upgradeTo"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Initialized"
      | "PoolCompoundEnabledUpdated"
      | "PoolPriceDeviationsUpdated"
      | "PoolRiskTiersUpdated"
      | "PoolWindowCapsUpdated"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "benchPool",
    values: [
      {
        poolId: BytesLike;
        baseAmount: BigNumberish;
        quoteAmount: BigNumberish;
        remark: string;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddressManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDependencyAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDependencyIdentifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "perBenchPool",
    values: [{ poolId: BytesLike; remark: string }]
  ): string;
  encodeFunctionData(
    functionFragment: "primePool",
    values: [{ poolId: BytesLike; initPrice: BigNumberish }]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerDependencies",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "trenchPool",
    values: [
      {
        poolId: BytesLike;
        oracleFeedId: BytesLike;
        oracleType: BigNumberish;
        maxPriceDeviation: BigNumberish;
        riskTier: BigNumberish;
        windowCapUsd: BigNumberish;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "unregisterDependencies",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePoolCompoundEnabled",
    values: [{ poolId: BytesLike; enabled: boolean }[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePoolPriceDeviations",
    values: [{ poolId: BytesLike; maxPriceDeviation: BigNumberish }[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePoolRiskTiers",
    values: [{ poolId: BytesLike; riskTier: BigNumberish }[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePoolWindowCaps",
    values: [{ poolId: BytesLike; windowCapUsd: BigNumberish }[]]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "benchPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAddressManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDependencyAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDependencyIdentifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "perBenchPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "primePool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerDependencies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "trenchPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unregisterDependencies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePoolCompoundEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePoolPriceDeviations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePoolRiskTiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePoolWindowCaps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolCompoundEnabledUpdatedEvent {
  export type InputTuple = [params: { poolId: BytesLike; enabled: boolean }[]];
  export type OutputTuple = [
    params: [poolId: string, enabled: boolean] &
      { poolId: string; enabled: boolean }[]
  ];
  export interface OutputObject {
    params: [string, boolean] & { poolId: string; enabled: boolean }[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolPriceDeviationsUpdatedEvent {
  export type InputTuple = [
    params: { poolId: BytesLike; maxPriceDeviation: BigNumberish }[]
  ];
  export type OutputTuple = [
    params: [poolId: string, maxPriceDeviation: bigint] &
      { poolId: string; maxPriceDeviation: bigint }[]
  ];
  export interface OutputObject {
    params: [string, bigint] & { poolId: string; maxPriceDeviation: bigint }[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolRiskTiersUpdatedEvent {
  export type InputTuple = [
    params: { poolId: BytesLike; riskTier: BigNumberish }[]
  ];
  export type OutputTuple = [
    params: [poolId: string, riskTier: bigint] &
      { poolId: string; riskTier: bigint }[]
  ];
  export interface OutputObject {
    params: [string, bigint] & { poolId: string; riskTier: bigint }[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolWindowCapsUpdatedEvent {
  export type InputTuple = [
    params: { poolId: BytesLike; windowCapUsd: BigNumberish }[]
  ];
  export type OutputTuple = [
    params: [poolId: string, windowCapUsd: bigint] &
      { poolId: string; windowCapUsd: bigint }[]
  ];
  export interface OutputObject {
    params: [string, bigint] & { poolId: string; windowCapUsd: bigint }[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PoolConfigurator extends BaseContract {
  connect(runner?: ContractRunner | null): PoolConfigurator;
  waitForDeployment(): Promise<this>;

  interface: PoolConfiguratorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  benchPool: TypedContractMethod<
    [
      params: {
        poolId: BytesLike;
        baseAmount: BigNumberish;
        quoteAmount: BigNumberish;
        remark: string;
      }
    ],
    [void],
    "nonpayable"
  >;

  getAddressManager: TypedContractMethod<[], [string], "view">;

  getDependencyAddress: TypedContractMethod<
    [identifier: BytesLike],
    [string],
    "view"
  >;

  getDependencyIdentifier: TypedContractMethod<
    [contractAddress: AddressLike],
    [string],
    "view"
  >;

  getImplementation: TypedContractMethod<[], [string], "view">;

  initialize: TypedContractMethod<
    [addressManager: AddressLike],
    [void],
    "nonpayable"
  >;

  perBenchPool: TypedContractMethod<
    [params: { poolId: BytesLike; remark: string }],
    [void],
    "nonpayable"
  >;

  primePool: TypedContractMethod<
    [params: { poolId: BytesLike; initPrice: BigNumberish }],
    [void],
    "nonpayable"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  registerDependencies: TypedContractMethod<
    [identifiers: BytesLike[]],
    [void],
    "nonpayable"
  >;

  trenchPool: TypedContractMethod<
    [
      params: {
        poolId: BytesLike;
        oracleFeedId: BytesLike;
        oracleType: BigNumberish;
        maxPriceDeviation: BigNumberish;
        riskTier: BigNumberish;
        windowCapUsd: BigNumberish;
      }
    ],
    [void],
    "nonpayable"
  >;

  unregisterDependencies: TypedContractMethod<
    [identifiers: BytesLike[]],
    [void],
    "nonpayable"
  >;

  updatePoolCompoundEnabled: TypedContractMethod<
    [params: { poolId: BytesLike; enabled: boolean }[]],
    [void],
    "nonpayable"
  >;

  updatePoolPriceDeviations: TypedContractMethod<
    [params: { poolId: BytesLike; maxPriceDeviation: BigNumberish }[]],
    [void],
    "nonpayable"
  >;

  updatePoolRiskTiers: TypedContractMethod<
    [params: { poolId: BytesLike; riskTier: BigNumberish }[]],
    [void],
    "nonpayable"
  >;

  updatePoolWindowCaps: TypedContractMethod<
    [params: { poolId: BytesLike; windowCapUsd: BigNumberish }[]],
    [void],
    "nonpayable"
  >;

  upgradeTo: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "benchPool"
  ): TypedContractMethod<
    [
      params: {
        poolId: BytesLike;
        baseAmount: BigNumberish;
        quoteAmount: BigNumberish;
        remark: string;
      }
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAddressManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getDependencyAddress"
  ): TypedContractMethod<[identifier: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getDependencyIdentifier"
  ): TypedContractMethod<[contractAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getImplementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[addressManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "perBenchPool"
  ): TypedContractMethod<
    [params: { poolId: BytesLike; remark: string }],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "primePool"
  ): TypedContractMethod<
    [params: { poolId: BytesLike; initPrice: BigNumberish }],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerDependencies"
  ): TypedContractMethod<[identifiers: BytesLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trenchPool"
  ): TypedContractMethod<
    [
      params: {
        poolId: BytesLike;
        oracleFeedId: BytesLike;
        oracleType: BigNumberish;
        maxPriceDeviation: BigNumberish;
        riskTier: BigNumberish;
        windowCapUsd: BigNumberish;
      }
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unregisterDependencies"
  ): TypedContractMethod<[identifiers: BytesLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePoolCompoundEnabled"
  ): TypedContractMethod<
    [params: { poolId: BytesLike; enabled: boolean }[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatePoolPriceDeviations"
  ): TypedContractMethod<
    [params: { poolId: BytesLike; maxPriceDeviation: BigNumberish }[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatePoolRiskTiers"
  ): TypedContractMethod<
    [params: { poolId: BytesLike; riskTier: BigNumberish }[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatePoolWindowCaps"
  ): TypedContractMethod<
    [params: { poolId: BytesLike; windowCapUsd: BigNumberish }[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeTo"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "PoolCompoundEnabledUpdated"
  ): TypedContractEvent<
    PoolCompoundEnabledUpdatedEvent.InputTuple,
    PoolCompoundEnabledUpdatedEvent.OutputTuple,
    PoolCompoundEnabledUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PoolPriceDeviationsUpdated"
  ): TypedContractEvent<
    PoolPriceDeviationsUpdatedEvent.InputTuple,
    PoolPriceDeviationsUpdatedEvent.OutputTuple,
    PoolPriceDeviationsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PoolRiskTiersUpdated"
  ): TypedContractEvent<
    PoolRiskTiersUpdatedEvent.InputTuple,
    PoolRiskTiersUpdatedEvent.OutputTuple,
    PoolRiskTiersUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PoolWindowCapsUpdated"
  ): TypedContractEvent<
    PoolWindowCapsUpdatedEvent.InputTuple,
    PoolWindowCapsUpdatedEvent.OutputTuple,
    PoolWindowCapsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "PoolCompoundEnabledUpdated(tuple[])": TypedContractEvent<
      PoolCompoundEnabledUpdatedEvent.InputTuple,
      PoolCompoundEnabledUpdatedEvent.OutputTuple,
      PoolCompoundEnabledUpdatedEvent.OutputObject
    >;
    PoolCompoundEnabledUpdated: TypedContractEvent<
      PoolCompoundEnabledUpdatedEvent.InputTuple,
      PoolCompoundEnabledUpdatedEvent.OutputTuple,
      PoolCompoundEnabledUpdatedEvent.OutputObject
    >;

    "PoolPriceDeviationsUpdated(tuple[])": TypedContractEvent<
      PoolPriceDeviationsUpdatedEvent.InputTuple,
      PoolPriceDeviationsUpdatedEvent.OutputTuple,
      PoolPriceDeviationsUpdatedEvent.OutputObject
    >;
    PoolPriceDeviationsUpdated: TypedContractEvent<
      PoolPriceDeviationsUpdatedEvent.InputTuple,
      PoolPriceDeviationsUpdatedEvent.OutputTuple,
      PoolPriceDeviationsUpdatedEvent.OutputObject
    >;

    "PoolRiskTiersUpdated(tuple[])": TypedContractEvent<
      PoolRiskTiersUpdatedEvent.InputTuple,
      PoolRiskTiersUpdatedEvent.OutputTuple,
      PoolRiskTiersUpdatedEvent.OutputObject
    >;
    PoolRiskTiersUpdated: TypedContractEvent<
      PoolRiskTiersUpdatedEvent.InputTuple,
      PoolRiskTiersUpdatedEvent.OutputTuple,
      PoolRiskTiersUpdatedEvent.OutputObject
    >;

    "PoolWindowCapsUpdated(tuple[])": TypedContractEvent<
      PoolWindowCapsUpdatedEvent.InputTuple,
      PoolWindowCapsUpdatedEvent.OutputTuple,
      PoolWindowCapsUpdatedEvent.OutputObject
    >;
    PoolWindowCapsUpdated: TypedContractEvent<
      PoolWindowCapsUpdatedEvent.InputTuple,
      PoolWindowCapsUpdatedEvent.OutputTuple,
      PoolWindowCapsUpdatedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
