/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface QuotePoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "EXCHANGE_RATE_PRECISION"
      | "POOL_TOKEN_DECIMALS"
      | "UPGRADE_INTERFACE_VERSION"
      | "deposit"
      | "distribute"
      | "getAddressManager"
      | "getDependencyAddress"
      | "getDependencyIdentifier"
      | "getExchangeRate(bytes32)"
      | "getExchangeRate(bytes32,uint256)"
      | "getImplementation"
      | "getPoolTokenPrice"
      | "initialize"
      | "pendingUserRebates"
      | "previewLpAmountOut"
      | "previewPoolTokenPrice"
      | "previewQuoteAmountOut"
      | "previewUserWithdrawData"
      | "proxiableUUID"
      | "registerDependencies"
      | "unregisterDependencies"
      | "upgradeTo"
      | "upgradeToAndCall"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Initialized"
      | "QuotePoolProfitDistributed"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "EXCHANGE_RATE_PRECISION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "POOL_TOKEN_DECIMALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BytesLike, BigNumberish, BigNumberish, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distribute",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddressManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDependencyAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDependencyIdentifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getExchangeRate(bytes32)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getExchangeRate(bytes32,uint256)",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolTokenPrice",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingUserRebates",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "previewLpAmountOut",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "previewPoolTokenPrice",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "previewQuoteAmountOut",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "previewUserWithdrawData",
    values: [BytesLike, BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerDependencies",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "unregisterDependencies",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BytesLike, BigNumberish, BigNumberish, AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "EXCHANGE_RATE_PRECISION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "POOL_TOKEN_DECIMALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "distribute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAddressManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDependencyAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDependencyIdentifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExchangeRate(bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExchangeRate(bytes32,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolTokenPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingUserRebates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewLpAmountOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewPoolTokenPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewQuoteAmountOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewUserWithdrawData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerDependencies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unregisterDependencies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuotePoolProfitDistributedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    amount: BigNumberish,
    genesisAmount: BigNumberish,
    price: BigNumberish,
    exchangeRate: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    amount: bigint,
    genesisAmount: bigint,
    price: bigint,
    exchangeRate: bigint
  ];
  export interface OutputObject {
    poolId: string;
    amount: bigint;
    genesisAmount: bigint;
    price: bigint;
    exchangeRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface QuotePool extends BaseContract {
  connect(runner?: ContractRunner | null): QuotePool;
  waitForDeployment(): Promise<this>;

  interface: QuotePoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  EXCHANGE_RATE_PRECISION: TypedContractMethod<[], [bigint], "view">;

  POOL_TOKEN_DECIMALS: TypedContractMethod<[], [bigint], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  deposit: TypedContractMethod<
    [
      poolId: BytesLike,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish,
      user: AddressLike,
      recipient: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  distribute: TypedContractMethod<
    [
      poolId: BytesLike,
      amount: BigNumberish,
      genesisAmount: BigNumberish,
      price: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getAddressManager: TypedContractMethod<[], [string], "view">;

  getDependencyAddress: TypedContractMethod<
    [identifier: BytesLike],
    [string],
    "view"
  >;

  getDependencyIdentifier: TypedContractMethod<
    [contractAddress: AddressLike],
    [string],
    "view"
  >;

  "getExchangeRate(bytes32)": TypedContractMethod<
    [poolId: BytesLike],
    [bigint],
    "view"
  >;

  "getExchangeRate(bytes32,uint256)": TypedContractMethod<
    [poolId: BytesLike, price: BigNumberish],
    [bigint],
    "view"
  >;

  getImplementation: TypedContractMethod<[], [string], "view">;

  getPoolTokenPrice: TypedContractMethod<
    [poolId: BytesLike, price: BigNumberish],
    [bigint],
    "view"
  >;

  initialize: TypedContractMethod<
    [addressManager: AddressLike],
    [void],
    "nonpayable"
  >;

  pendingUserRebates: TypedContractMethod<
    [poolId: BytesLike, user: AddressLike, price: BigNumberish],
    [bigint],
    "view"
  >;

  previewLpAmountOut: TypedContractMethod<
    [poolId: BytesLike, amountIn: BigNumberish, price: BigNumberish],
    [bigint],
    "view"
  >;

  previewPoolTokenPrice: TypedContractMethod<
    [poolId: BytesLike],
    [bigint],
    "view"
  >;

  previewQuoteAmountOut: TypedContractMethod<
    [poolId: BytesLike, amountIn: BigNumberish, price: BigNumberish],
    [bigint],
    "view"
  >;

  previewUserWithdrawData: TypedContractMethod<
    [
      poolId: BytesLike,
      lpAmountIn: BigNumberish,
      user: AddressLike,
      price: BigNumberish
    ],
    [bigint],
    "view"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  registerDependencies: TypedContractMethod<
    [identifiers: BytesLike[]],
    [void],
    "nonpayable"
  >;

  unregisterDependencies: TypedContractMethod<
    [identifiers: BytesLike[]],
    [void],
    "nonpayable"
  >;

  upgradeTo: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  withdraw: TypedContractMethod<
    [
      poolId: BytesLike,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish,
      user: AddressLike,
      recipient: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "EXCHANGE_RATE_PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "POOL_TOKEN_DECIMALS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [
      poolId: BytesLike,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish,
      user: AddressLike,
      recipient: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distribute"
  ): TypedContractMethod<
    [
      poolId: BytesLike,
      amount: BigNumberish,
      genesisAmount: BigNumberish,
      price: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAddressManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getDependencyAddress"
  ): TypedContractMethod<[identifier: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getDependencyIdentifier"
  ): TypedContractMethod<[contractAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getExchangeRate(bytes32)"
  ): TypedContractMethod<[poolId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getExchangeRate(bytes32,uint256)"
  ): TypedContractMethod<
    [poolId: BytesLike, price: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getImplementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPoolTokenPrice"
  ): TypedContractMethod<
    [poolId: BytesLike, price: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[addressManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pendingUserRebates"
  ): TypedContractMethod<
    [poolId: BytesLike, user: AddressLike, price: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "previewLpAmountOut"
  ): TypedContractMethod<
    [poolId: BytesLike, amountIn: BigNumberish, price: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "previewPoolTokenPrice"
  ): TypedContractMethod<[poolId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "previewQuoteAmountOut"
  ): TypedContractMethod<
    [poolId: BytesLike, amountIn: BigNumberish, price: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "previewUserWithdrawData"
  ): TypedContractMethod<
    [
      poolId: BytesLike,
      lpAmountIn: BigNumberish,
      user: AddressLike,
      price: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerDependencies"
  ): TypedContractMethod<[identifiers: BytesLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unregisterDependencies"
  ): TypedContractMethod<[identifiers: BytesLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeTo"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [
      poolId: BytesLike,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish,
      user: AddressLike,
      recipient: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "QuotePoolProfitDistributed"
  ): TypedContractEvent<
    QuotePoolProfitDistributedEvent.InputTuple,
    QuotePoolProfitDistributedEvent.OutputTuple,
    QuotePoolProfitDistributedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "QuotePoolProfitDistributed(bytes32,uint256,uint256,uint256,uint256)": TypedContractEvent<
      QuotePoolProfitDistributedEvent.InputTuple,
      QuotePoolProfitDistributedEvent.OutputTuple,
      QuotePoolProfitDistributedEvent.OutputObject
    >;
    QuotePoolProfitDistributed: TypedContractEvent<
      QuotePoolProfitDistributedEvent.InputTuple,
      QuotePoolProfitDistributedEvent.OutputTuple,
      QuotePoolProfitDistributedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
