export const COMMON_PRICE_DISPLAY_DECIMALS = 2
export const COMMON_BASE_DISPLAY_DECIMALS = 4
export const COMMON_PERCENT_DISPLAY_DECIMALS = 2

export const FUNDING_FEE_TRACKER_DECIMALS = 8

export const TRADING_FEE_DECIMALS = 8
