export const COMMON_CONFIG_DECIMALS = 8

export const FUNDING_RATE_PERCENT_DISPLAY_DECIMALS = 4

export const COMMON_PERCENT_DISPLAY_DECIMALS = 2

export const COMMON_PRICE_DECIMALS = 30
export const COMMON_LP_AMOUNT_DECIMALS = 18
export const COMMON_PRICE_DISPLAY_DECIMALS = 2

export const MYX_TOKEN_DECIMALS = 18


export const COMMON_NETWORK_FEE_DISPLAY_DECIMALS = 6
export const COMMON_NATIVE_TOKEN_DECIMALS = 18

export const FEE_RATE_PERCENT_DISPLAY_DECIMALS = 4

export const VIP_PROFITS_PRECISION = 2

export const COMMON_USD_ASSETS_LABEL = 'USD'
