/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  PoolConfigurator,
  PoolConfiguratorInterface,
} from "../PoolConfigurator";

const _abi = [
  {
    type: "error",
    name: "AddressEmptyCode",
    inputs: [
      {
        type: "address",
        name: "target",
      },
    ],
  },
  {
    type: "error",
    name: "ERC1967InvalidImplementation",
    inputs: [
      {
        type: "address",
        name: "implementation",
      },
    ],
  },
  {
    type: "error",
    name: "ERC1967NonPayable",
    inputs: [],
  },
  {
    type: "error",
    name: "FailedCall",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidInitialization",
    inputs: [],
  },
  {
    type: "error",
    name: "NotDependencyManager",
    inputs: [],
  },
  {
    type: "error",
    name: "NotInitializing",
    inputs: [],
  },
  {
    type: "error",
    name: "NotProxyAdmin",
    inputs: [],
  },
  {
    type: "error",
    name: "PermissionDenied",
    inputs: [
      {
        type: "address",
        name: "caller",
      },
      {
        type: "address",
        name: "target",
      },
    ],
  },
  {
    type: "error",
    name: "UUPSUnauthorizedCallContext",
    inputs: [],
  },
  {
    type: "error",
    name: "UUPSUnsupportedProxiableUUID",
    inputs: [
      {
        type: "bytes32",
        name: "slot",
      },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "Initialized",
    inputs: [
      {
        type: "uint64",
        name: "version",
        indexed: false,
      },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "PoolCompoundEnabledUpdated",
    inputs: [
      {
        type: "tuple[]",
        name: "params",
        indexed: false,
        components: [
          {
            type: "bytes32",
            name: "poolId",
          },
          {
            type: "bool",
            name: "enabled",
          },
        ],
      },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "PoolPriceDeviationsUpdated",
    inputs: [
      {
        type: "tuple[]",
        name: "params",
        indexed: false,
        components: [
          {
            type: "bytes32",
            name: "poolId",
          },
          {
            type: "uint16",
            name: "maxPriceDeviation",
          },
        ],
      },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "PoolRiskTiersUpdated",
    inputs: [
      {
        type: "tuple[]",
        name: "params",
        indexed: false,
        components: [
          {
            type: "bytes32",
            name: "poolId",
          },
          {
            type: "uint8",
            name: "riskTier",
          },
        ],
      },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "PoolWindowCapsUpdated",
    inputs: [
      {
        type: "tuple[]",
        name: "params",
        indexed: false,
        components: [
          {
            type: "bytes32",
            name: "poolId",
          },
          {
            type: "uint128",
            name: "windowCapUsd",
          },
        ],
      },
    ],
  },
  {
    type: "event",
    anonymous: false,
    name: "Upgraded",
    inputs: [
      {
        type: "address",
        name: "implementation",
        indexed: true,
      },
    ],
  },
  {
    type: "function",
    name: "UPGRADE_INTERFACE_VERSION",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [
      {
        type: "string",
      },
    ],
  },
  {
    type: "function",
    name: "benchPool",
    constant: false,
    payable: false,
    inputs: [
      {
        type: "tuple",
        name: "params",
        components: [
          {
            type: "bytes32",
            name: "poolId",
          },
          {
            type: "uint256",
            name: "baseAmount",
          },
          {
            type: "uint256",
            name: "quoteAmount",
          },
          {
            type: "string",
            name: "remark",
          },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getAddressManager",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [
      {
        type: "address",
      },
    ],
  },
  {
    type: "function",
    name: "getDependencyAddress",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [
      {
        type: "bytes32",
        name: "identifier",
      },
    ],
    outputs: [
      {
        type: "address",
      },
    ],
  },
  {
    type: "function",
    name: "getDependencyIdentifier",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [
      {
        type: "address",
        name: "contractAddress",
      },
    ],
    outputs: [
      {
        type: "bytes32",
      },
    ],
  },
  {
    type: "function",
    name: "getImplementation",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [
      {
        type: "address",
      },
    ],
  },
  {
    type: "function",
    name: "initialize",
    constant: false,
    payable: false,
    inputs: [
      {
        type: "address",
        name: "addressManager",
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "perBenchPool",
    constant: false,
    payable: false,
    inputs: [
      {
        type: "tuple",
        name: "params",
        components: [
          {
            type: "bytes32",
            name: "poolId",
          },
          {
            type: "string",
            name: "remark",
          },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "primePool",
    constant: false,
    payable: false,
    inputs: [
      {
        type: "tuple",
        name: "params",
        components: [
          {
            type: "bytes32",
            name: "poolId",
          },
          {
            type: "uint256",
            name: "initPrice",
          },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "proxiableUUID",
    constant: true,
    stateMutability: "view",
    payable: false,
    inputs: [],
    outputs: [
      {
        type: "bytes32",
      },
    ],
  },
  {
    type: "function",
    name: "registerDependencies",
    constant: false,
    payable: false,
    inputs: [
      {
        type: "bytes32[]",
        name: "identifiers",
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "trenchPool",
    constant: false,
    payable: false,
    inputs: [
      {
        type: "tuple",
        name: "params",
        components: [
          {
            type: "bytes32",
            name: "poolId",
          },
          {
            type: "bytes32",
            name: "oracleFeedId",
          },
          {
            type: "uint8",
            name: "oracleType",
          },
          {
            type: "uint16",
            name: "maxPriceDeviation",
          },
          {
            type: "uint8",
            name: "riskTier",
          },
          {
            type: "uint128",
            name: "windowCapUsd",
          },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "unregisterDependencies",
    constant: false,
    payable: false,
    inputs: [
      {
        type: "bytes32[]",
        name: "identifiers",
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "updatePoolCompoundEnabled",
    constant: false,
    payable: false,
    inputs: [
      {
        type: "tuple[]",
        name: "params",
        components: [
          {
            type: "bytes32",
            name: "poolId",
          },
          {
            type: "bool",
            name: "enabled",
          },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "updatePoolPriceDeviations",
    constant: false,
    payable: false,
    inputs: [
      {
        type: "tuple[]",
        name: "params",
        components: [
          {
            type: "bytes32",
            name: "poolId",
          },
          {
            type: "uint16",
            name: "maxPriceDeviation",
          },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "updatePoolRiskTiers",
    constant: false,
    payable: false,
    inputs: [
      {
        type: "tuple[]",
        name: "params",
        components: [
          {
            type: "bytes32",
            name: "poolId",
          },
          {
            type: "uint8",
            name: "riskTier",
          },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "updatePoolWindowCaps",
    constant: false,
    payable: false,
    inputs: [
      {
        type: "tuple[]",
        name: "params",
        components: [
          {
            type: "bytes32",
            name: "poolId",
          },
          {
            type: "uint128",
            name: "windowCapUsd",
          },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "upgradeTo",
    constant: false,
    stateMutability: "payable",
    payable: true,
    inputs: [
      {
        type: "address",
        name: "newImplementation",
      },
      {
        type: "bytes",
        name: "data",
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "upgradeToAndCall",
    constant: false,
    stateMutability: "payable",
    payable: true,
    inputs: [
      {
        type: "address",
        name: "newImplementation",
      },
      {
        type: "bytes",
        name: "data",
      },
    ],
    outputs: [],
  },
] as const;

export class PoolConfigurator__factory {
  static readonly abi = _abi;
  static createInterface(): PoolConfiguratorInterface {
    return new Interface(_abi) as PoolConfiguratorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): PoolConfigurator {
    return new Contract(address, _abi, runner) as unknown as PoolConfigurator;
  }
}
